use_frameworks!

target 'DevOptions_Example' do
  pod 'TRZSlideLicenseViewController'
  pod 'Toast-Swift'
  pod 'SnapKit'
  pod 'DevOptions', :path => '../'
  platform :ios, '10.0'
  
  target 'DevOptions_Tests' do
    inherit! :search_paths
	
    
  end
end
